---

- hosts: all
  become: true
  tasks:
    - name: install apche and php
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
        update_cache: true
